# Generated by Django 5.2.1 on 2025-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='andhra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=255)),
                ('masalaused', models.CharField(max_length=255)),
                ('vegitablesused', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='northindian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=255)),
                ('masalaused', models.CharField(max_length=255)),
                ('vegitablesused', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=255)),
                ('masalaused', models.CharField(max_length=255)),
                ('vegitablesused', models.CharField(max_length=255)),
            ],
        ),
    ]
